apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-pvc
  namespace: kaiwangke-dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gp3
