# These can also be created from the command line using environment variables
#
# kubectl create secret generic redis-creds --from-literal=uri=$DATABASE_URI
#
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  password: bXlwYXNzd2Rmb3Jwcm9tb3Rpb250ZWFt
  uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjY2NjYvcG9zdGdyZXM=

# kubectl create secret generic postgres-creds --from-literal=POSTGRES_PASSWORD=bXlwYXNzd2Rmb3Jwcm9tb3Rpb250ZWFt --from-literal=uri=cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjY2NjYvcG9zdGdyZXM= 