---
# Python 3 with PostgreSQL
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile    
    hostname: nyu
    container_name: project
    volumes:
      - ..:/app
      # - ~/.bluemix/apikey-project.json:/home/vscode/apikey.json
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      FLASK_DEBUG: "True"
      PORT: 8000
      DATABASE_URI: postgresql://promotion:postgres@postgres:5432/promotion
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    # Uncomment ports to access database from your computer (optional)
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: promotion
      POSTGRES_DB: promotion
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  postgres:

networks:
  dev:
